export const SUBMIT_FORM = 'SUBMIT_FORM';
export const REQUEST_AVAILABILITY = 'REQUEST_AVAILABILTY';
export const RECEIVE_AVAILABILITY = 'RECEIVE_AVAILABILTY';
export const RECEIVE_AVAILABILITY_FAILURE = 'RECEIVE_AVAILABILTY_FAILURE';

export const REQUEST_RESPONDING_MEETINGS = 'REQUEST_RESPONDING_MEETINGS';
export const RECEIVE_RESPONDING_MEETINGS_SUCCESS = 'RECEIVE_RESPONDING_MEETINGS_SUCCESS';
export const RECEIVE_RESPONDING_MEETINGS_FAILURE = 'RECEIVE_RESPONDING_MEETINGS_FAILURE';

// Users
export const SET_USER = 'SET_USER';
export const CLEAR_USERS = 'CLEAR_USERS';
