export const SUBMIT_FORM = 'SUBMIT_FORM';
export const REQUEST_AVAILABILITY = 'REQUEST_AVAILABILTY';
export const RECEIVE_AVAILABILITY = 'RECEIVE_AVAILABILTY';
export const RECEIVE_AVAILABILITY_FAILURE = 'RECEIVE_AVAILABILTY_FAILURE';
