export const SUBMIT_FORM = 'SUBMIT_FORM';
export const REQUEST_AVAILABILITY = 'REQUEST_AVAILABILTY';
export const RECEIVE_AVAILABILITY = 'RECEIVE_AVAILABILTY';
export const RECEIVE_AVAILABILITY_FAILURE = 'RECEIVE_AVAILABILTY_FAILURE';

export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER_SUCCESS = 'RECEIVE_USER';
export const RECEIVE_USER_FAILURE = 'RECEIVE_USER_FAILURE';
export const LOG_OUT = 'LOG_OUT';
